// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJxtIiR2Dv9GZs6WaUmUQer5Nn7xij0Us',
    appId: '1:183889231929:web:6fc2b40949c22ab5618de8',
    messagingSenderId: '183889231929',
    projectId: 'shopapp-e4355',
    authDomain: 'shopapp-e4355.firebaseapp.com',
    storageBucket: 'shopapp-e4355.firebasestorage.app',
    measurementId: 'G-EBTYRE7E29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGTTL3ho3nC1pq8CEZ3gJ1z6MRyN789DA',
    appId: '1:183889231929:android:0befc27f3ef270a5618de8',
    messagingSenderId: '183889231929',
    projectId: 'shopapp-e4355',
    storageBucket: 'shopapp-e4355.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJo8Eih4W2GZY9iReNKTgiOGnwgJG-Unc',
    appId: '1:183889231929:ios:338950c968706de6618de8',
    messagingSenderId: '183889231929',
    projectId: 'shopapp-e4355',
    storageBucket: 'shopapp-e4355.firebasestorage.app',
    iosBundleId: 'com.example.shoppingapp',
  );
}
